### ISSUE TITLE
Reprogramming bugs

### ISSUE THREAD

**Issue by wycc** [wukong-m2m/wukong-darjeeling#162]
When we deploty the table to wudevice, we will call
- open
- a couple of write
- commit
- reboot

Currently, the code does not consider the possibility of retransmission. We implement retransmit in the application level. However, the low layer will do retransmit as well. It means that we may receive duplicated open/write/commit/reboot message.

The current problem is in the commit. when we receive duplicated commit, it will write to the address 0, which is the interrupt vector table and some other important data. In this case, we may see a factory default or even wosrse, the wudevice will become unusable completely.

**Comment by nielsreijers** [comment]
Hi,

Just got curious about this issue, since there's some code to check if the
commit message matches the current write position (to detect dropped
packets). But it seems I forgot to reset that position in wkreprog_comm.c,
around line 85. Maybe good to add as well. Sorry for the bug. :-)

Best,
 Niels

PS. Also, could we please not use DEBUG_LOG(true anymore?

On Fri, Aug 15, 2014 at 6:48 PM, chingchichuang notifications@github.com
wrote:

> Closed #162 https://github.com/wukong-m2m/wukong-darjeeling/issues/162
> via f3d4a1e
> https://github.com/wukong-m2m/wukong-darjeeling/commit/f3d4a1e6e068db2449add423529d4b8a7e954ea4
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wukong-m2m/wukong-darjeeling/issues/162#event-153383384
> .

## 

_
