### ISSUE TITLE
data.ops not defined

### ISSUE THREAD

**Issue by senatorjo** [wukong-m2m/wukong-darjeeling#44]
In offline mode, if we go to the node editor tab. There will be an error reported in poll() function, "data.ops.indexOf('c')", will report," data.ops not defined"
 $.post(url, {version: version}, function(data) {
        if (typeof callback != 'undefined') {
            callback(data);
        }
        if (data.ops.indexOf('c') != -1) {
Uncaught TypeError: Cannot call method 'indexOf' of undefined
            stop_polling();
        } else if (forceRepeat) {
            setTimeout(function() {
                poll(url, data.version, options, callback);
            }, 1000);
        }

**Comment by pencilcheck** [comment]
which branch and commit are you in?

My poll function looks like this in the latest commit of branch merge-features

410     $.post(url, {version: version}, function(data) {¬
411         if (typeof callback != 'undefined') {¬
412             callback(data);¬
413         }¬
414 ¬
415         if (data && data.ops && data.ops.indexOf('c') != -1) {¬
416             stop_polling();¬
417         } else if (forceRepeat) {¬
418             setTimeout(function() {¬
419                 poll(url, data.version, options, callback);¬
420             }, 1000);¬
421         }¬
422 ¬
423         global_polling_status = false;¬
424     });¬

Since this is simply just not updating the code to the latest commit, I will close this one. Please reopen if you still find this error.
